services:
  nova-akademija:
    build:
      context: .
      args:
        - VITE_WEB3FORMS_ACCESS_KEY=600f6776-ced9-416d-bd21-a6c5b66c8dec
    container_name: nova-akademija
    restart: unless-stopped
    ports:
      - 4231:8080
